version: '3'
services:

  spring-boot-metrics:
    #image: java-metrics_spring-boot-metrics
    build:
      context: "."
      args:
        JAR_FILE: target/spring-boot-metrics.jar # use 'mvn package' to generate the jar
    ports:
      - "8080:8080"
    container_name: spring-boot-metrics
    networks:
      - my-network

  prometheus:
    build: "./prometheus"
    ports:
      - "9090:9090"
    container_name: prometheus
    networks:
      - my-network

  grafana:
    build: "./grafana"
    ports:
      - "3000:3000"
    container_name: grafana
    networks:
      - my-network

networks:
  my-network:

