name: Java build CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: xlui/action-maven-cli/jdk11@master
      with:
          java-version: 1.8
    - name: Compile with Maven
      run: mvn -B -U compile
    - name: Test (only Unit Tests)
      run: mvn -B -U test
